### ISSUE TITLE
Launching Jekyll demo site shows me file directory

### ISSUE THREAD

**Issue by csharpee** [bluszcz/jekyll-strapi#14]
![image](https://user-images.githubusercontent.com/18726788/175346170-b3b06c41-2ecd-4457-84cb-7438fb096bb8.png)

**Comment by csharpee** [comment]
most likely related to either baseurl or layout type. Could be similar to PR #19

**Comment by bluszcz** [comment]
Code is configure to work in 'jekyll-strapi' context and I guess is properly configure, since sandbox environment of github has no problem to build it: https://bluszcz.github.io/jekyll-strapi/
