### ISSUE TITLE
Jekyll-Strapi-ng.drawio.png not found

### ISSUE THREAD

**Issue by csharpee** [bluszcz/jekyll-strapi#18]
`jekyll-strapi-jekyll-serve-1  | [2022-06-23 11:38:43] ERROR `/assets/images/jekyll-strapi-ng.drawio.png' not found.`

![image](https://user-images.githubusercontent.com/18726788/175350780-6c3c0c0a-641c-48fc-94ea-aa6962ae04f6.png)

**Comment by bluszcz** [comment]
1. Docs have been configured to launch in default context of github page: https://bluszcz.github.io/jekyll-strapi/ - and they are running without errors by Github Actions/. 
2. Your bug report is missing information what you have launched.
